project_scoping_task:
  description: >
    Scope out a set of projects for a team of software engineering interns.
    The projects should be open source and suitable for beginners.
    They should gradually introduce the interns to more complex concepts.
    Use the repo's issues, discussions, README, and codebase to evaluate the project.

  expected_output: >
    A list of 3-5 open source projects that are suitable for beginners.
    Each project should have a brief description, a list of issues suitable for beginners,
    and a list of resources to help the interns get started.

