project_scoping_task:
  description: >
    Scope out a set of projects for a team of software engineering interns working on {repo}
    The projects should be suitable for beginners.
    They should gradually introduce the interns to more complex concepts.
    They also should have a good chance of being accepted by the community.
    Use the repo's issues, discussions, README, and codebase to evaluate the project.

  expected_output: >
    A list of 3-5 open source projects that are suitable for beginners.
    Each project should have a brief description, a list of issues suitable for beginners,
    a list of resources to help the interns get started, and high level design of a solution for the project.

